Models/BaseModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dojo_League.Models
{
    public abstract class BaseEntity {

        [Required(ErrorMessage = "Name is required!")]
        public string Name { get; set; }
        
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
    }
}

Models/DojoBundleModel.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Dojo_League.Models
{
    public class DojoBundle
    {
        public Dojo Dojo { get; set; }

        public List<Dojo> Dojos { get; set; }

        public List<Ninja> Members { get; set; }

        public List<Ninja> Rogue { get; set; }
        

        public DojoBundle(DojoLeagueContext _context)
        {
            Dojo = new Dojo();
            Dojos = _context.dojos.Where(d => d.DojoId != 0).ToList();
        }

        public DojoBundle(DojoLeagueContext _context, Dojo dojo)
        {
            Dojo = dojo;
            Dojos = _context.dojos.Where(d => d.DojoId != 0).ToList();
        }

        public DojoBundle(DojoLeagueContext _context, int DojoId)
        {
            Dojo = _context.dojos.Where(d => d.DojoId == DojoId).SingleOrDefault();
            Members = _context.ninjas.Where(d => d.DojoId == DojoId).ToList();
            Rogue = _context.ninjas.Where(d => d.DojoId == 0).ToList();
        }
    }
}

Models/DojoLeagueContext.cs
using Microsoft.EntityFrameworkCore;
 
namespace Dojo_League.Models
{
    public class DojoLeagueContext : DbContext
    {
        // base() calls the parent class' constructor passing the "options" parameter along
        public DojoLeagueContext(DbContextOptions<DojoLeagueContext> options) : base(options) { }

         public DbSet<Ninja> ninjas { get; set; }
         public DbSet<Dojo> dojos { get; set; }
    }
}

Models/DojoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dojo_League.Models
{
    public class Dojo : BaseEntity
    {
        [Key]
        public int DojoId { get; set; }

        [Required(ErrorMessage = "Dojo Location is required!")]
        [Display(Name = "Dojo Location: ")]
        public string Location { get; set; }
        

        [Display(Name = "Additional Information: ")]
        public string Info { get; set; }

        public List<Ninja> Ninjas { get; set; }
 
        public Dojo()
        {
            Ninjas = new List<Ninja>();
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Dojo_League.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/NinjaBundleModel.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Dojo_League.Models
{
    public class NinjaBundle
    {
        public List<Ninja> Ninjas { get; set; }
        public Ninja Ninja { get; set; }

        public List<Dojo> Dojos { get; set; }

        public NinjaBundle(DojoLeagueContext _context)
        {
            Ninja = new Ninja();
            Ninjas = _context.ninjas.Include(d => d.Dojo).ToList();
            Dojos = _context.dojos.ToList();
        }

        public NinjaBundle(DojoLeagueContext _context, Ninja ninja)
        {
            Ninja = ninja;
            Ninjas = _context.ninjas.Include(d => d.Dojo).ToList(); 
            Dojos = _context.dojos.ToList();
        }
    }
}

Models/NinjaModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dojo_League.Models
{
    public class Ninja : BaseEntity
    {
        [Key]
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Level is required!")]
        [Display(Name = "Ninja Level (1 -10): ")]
        [Range(1, 10, ErrorMessage = "Level is required!")]
        public int Level { get; set; }

        [Display(Name = "Optional Description: ")]
        public string Description { get; set; }

        [Display(Name = "Assigned Dojo: ")]
        public int DojoId { get; set; }
        public Dojo Dojo { get; set; }
 
    }
}

Controllers/LeagueController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Dojo_League.Models;
using Microsoft.EntityFrameworkCore;

namespace Dojo_League.Controllers
{
    public class LeagueController : Controller
    {
        private DojoLeagueContext _context;

        public LeagueController(DojoLeagueContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("")]
        [Route("Ninjas")]
        public IActionResult Ninjas()
        {
            return View(new NinjaBundle(_context));
        }

        [HttpGet]
        [Route("Dojos")]
        public IActionResult Dojos()
        {
            return View(new DojoBundle(_context));
        }

        [HttpPost]
        [Route("CreateNinja")]
        public IActionResult CreateNinja(Ninja ninja)
        {
            if(!ModelState.IsValid)
            {
                return View("Ninjas", new NinjaBundle(_context, ninja));
            }else{

                _context.ninjas.Add(ninja);
                _context.SaveChanges();

                return RedirectToAction("Ninjas");
            }
        }

        [HttpPost]
        [Route("CreateDojo")]
        public IActionResult CreateDojo(Dojo dojo)
        {
            if(!ModelState.IsValid)
            {
                return View("Dojos", new DojoBundle(_context, dojo));
            }else{

                _context.dojos.Add(dojo);
                _context.SaveChanges();

                return RedirectToAction("Dojos");
            }
        }

        [HttpGet]
        [Route("Ninja/{id}")]
        public IActionResult Ninja(int id)
        {
            Ninja ninja = _context.ninjas.Where(n => n.Id == id).Include(d => d.Dojo).SingleOrDefault();
            return View(ninja);
        }

        [HttpGet]
        [Route("Dojo/{id}")]
        public IActionResult Dojo(int id)
        {
            return View(new DojoBundle(_context, id));
        }

        [HttpGet]
        [Route("Recruite/{id}/{dojoId}")]
        public IActionResult Recruite(int id, int dojoId)
        {
            Ninja ninja = _context.ninjas.Where(n => n.Id == id).SingleOrDefault();
            ninja.DojoId = dojoId;
            _context.SaveChanges();

            return RedirectToAction("Dojo", new{ id = dojoId });
        }
        
        [HttpGet]
        [Route("Banish/{id}/{dojoId}")]
        public IActionResult Banish(int id, int dojoId)
        {
            Ninja ninja = _context.ninjas.Where(n => n.Id == id).SingleOrDefault();
            ninja.DojoId = 0;
            _context.SaveChanges();
            
            return RedirectToAction("Dojo", new{ id = dojoId });
        }
    }
}

Views/League/Dojo.cshtml
@model Dojo_League.Models.DojoBundle
@{
    ViewData["Title"] = @Model.Dojo.Name;
}

<div class="row mt-5">
    <div class="col-12">
        <h1>@Html.DisplayFor(modelItem => @Model.Dojo.Name)</h1>
        <h5 class="mt-4">Dojo Location - @Html.DisplayFor(modelItem => @Model.Dojo.Location)</h5>
        <h5 class="mt-4">Information - @Html.DisplayFor(modelItem => @Model.Dojo.Info)</h5>
    </div>
</div>
<div class="row mt-5">
    <div class="col-6">
        <h2 class="pb-3">Current Members</h2>
        <table class="table table-striped table-bordered table-dark">
            <thead>
                <tr>
                    <th class="w-75">Ninja</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach(Ninja member in @Model.Members)
                    {
                        <tr>
                            <td class="align-middle">@member.Name</td>
                            <td class="align-middle text-center"><a href="/Banish/@member.Id/@Model.Dojo.DojoId" class="btn btn-dark">Banish!</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="col-6">
        <h2 class="pb-3">Rogue Ninjas</h2>
        <table class="table table-striped table-bordered table-dark">
            <thead>
                <tr>
                    <th class="w-75">Ninja</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach(Ninja rogue in @Model.Rogue)
                    {
                        <tr>
                            <td class="align-middle">@rogue.Name</td>
                            <td class="align-middle text-center"><a href="/Recruite/@rogue.Id/@Model.Dojo.DojoId" class="btn btn-dark">Recruite!</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

Views/League/Dojos.cshtml
@model Dojo_League.Models.DojoBundle

@{
    ViewData["Title"] = "Dojos";
}

<div class="row mx-auto">
    <div class="col-4">
        <h1 class="my-5">All Dojos</h1>
        <table class="table table-striped table-bordered table-dark">
            <thead>
                <tr>
                    <th>Dojo Name</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach(Dojo dojo in @Model.Dojos)
                    {
                        <tr>
                            <td class="w-50"><a href="Dojo/@dojo.DojoId" class="text-white"><u>@Html.DisplayFor(modelItem => dojo.Name)</u></a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="col-8">
        <h1 class="my-5">Registered a Dojo</h1>
        <form asp-controller="League" asp-action="CreateDojo" method="post" class="form-control py-3">
            <div class="col-12 d-inline-block my-2">
                <label asp-for="@Model.Dojo.Name" class="d-inline-block col-3 p-0 align-top">Dojo Name: </label>
                <input asp-for="@Model.Dojo.Name" class="form-control d-inline-block col-8 m-auto" placeholder="Enter Dojo Name" aria-label="Enter Dojo Name" />
                <span asp-validation-for="@Model.Dojo.Name" class="d-block pl-3 offset-3 text-danger"></span>
            </div>
            <div class="col-12 d-inline-block my-2">
                <label asp-for="@Model.Dojo.Location" class="d-inline-block col-3 p-0 align-top"></label>
                <input asp-for="@Model.Dojo.Location" class="form-control d-inline-block col-8 m-auto" placeholder="Enter Dojo Location" aria-label="Enter Dojo Location" />
                <span asp-validation-for="@Model.Dojo.Location" class="d-block pl-3 offset-3 text-danger"></span>
            </div>
            <div class="col-12 d-inline-block my-2">
                <label asp-for="@Model.Dojo.Info" class="d-inline-block col-3 p-0 align-top"></label>
                <textarea asp-for="@Model.Dojo.Info" class="form-control d-inline-block col-8 m-auto" placeholder="Enter Additional Information" aria-label="Enter Additional Information"></textarea>
                <span asp-validation-for="@Model.Dojo.Info" class="d-block pl-3 offset-3 text-danger"></span>
            </div>
            <div class="row my-2 pr-5 justify-content-end">
                <button class="btn btn-dark" type="submit">Add Dojo</button>
            </div>
        </form>
    </div>
</div>

Views/League/Ninja.cshtml
@model Dojo_League.Models.Ninja
@{
    ViewData["Title"] = @Model.Name;
}

<div class="row mt-5">
    <div class="col-12">
        <h1>@Html.DisplayFor(modelItem => @Model.Name)</h1>
        <h5 class="mt-4">Ninja Level - @Html.DisplayFor(modelItem => @Model.Level)</h5>
        <h5 class="mt-4">Description: @Html.DisplayFor(modelItem => @Model.Description)</h5>
        <h5 class="mt-4">Current Dojo: 
        @{
            if(@Model.Dojo.DojoId == 0){
                @Html.DisplayFor(modelItem => @Model.Dojo.Name)
            }else{
                <a href="/Dojo/@Model.Dojo.DojoId">@Html.DisplayFor(modelItem => @Model.Dojo.Name)</a>
            }
        }
        </h5>
    </div>
</div>

Views/League/Ninjas.cshtml
@model Dojo_League.Models.NinjaBundle

@{
    ViewData["Title"] = "Ninjas";
}

<div class="row mx-auto">
    <div class="col-6">
        <h1 class="my-5">Registered Ninjas</h1>
        <table class="table table-striped table-bordered table-dark">
            <thead>
                <tr>
                    <th>Ninja Name</th>
                    <th>Home Dojo</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach(Ninja ninja in @Model.Ninjas)
                    {
                        <tr>
                            <td class="w-50"><a href="Ninja/@ninja.Id" class="text-white"><u>@Html.DisplayFor(modelItem => ninja.Name)</u></a></td>
                            @{
                                if(ninja.Dojo.Name == "Rogue"){
                                    <td>@Html.DisplayFor(modelItem => ninja.Dojo.Name)</td>
                                }else{
                                    <td><a href="Dojo/@ninja.DojoId" class="text-white"><u>@Html.DisplayFor(modelItem => ninja.Dojo.Name)</u></a></td>
                                }
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="col-6">
        <h1 class="my-5">Registered a Ninja</h1>
        <form asp-controller="League" asp-action="CreateNinja" method="post" class="form-control py-3">
            <div class="col-12 d-inline-block my-2">
                <label asp-for="@Model.Ninja.Name" class="d-inline-block col-3 p-0 align-top">Ninja Name: </label>
                <input asp-for="@Model.Ninja.Name" class="form-control d-inline-block col-8 m-auto" placeholder="Enter Ninja Name" aria-label="Enter Ninja Name" />
                <span asp-validation-for="@Model.Ninja.Name" class="d-block pl-3 offset-3 text-danger"></span>
            </div>
            <div class="col-12 d-inline-block my-2">
                <label asp-for="@Model.Ninja.Level" class="d-inline-block col-3 p-0 align-top"></label>
                <select asp-for="@Model.Ninja.Level" class="form-control d-inline-block col-2 m-auto">
                    <option value="-" selected hidden disabled> - </option>
                    @{
                        for (int i = 1; i <= 10; i++)
                        {
                            <option value="@i">@i</option>
                        }
                    }
                </select>
                <span asp-validation-for="@Model.Ninja.Level" class="d-block pl-3 offset-3 text-danger"></span>
            </div>
            <div class="col-12 d-inline-block my-2">
                <label asp-for="@Model.Ninja.DojoId" class="d-inline-block col-3 p-0 align-top"></label>
                <select asp-for="@Model.Ninja.DojoId" class="form-control d-inline-block col-8 m-auto">
                    @{
                        foreach(Dojo dojo in @Model.Dojos)
                        {
                            if(@dojo.Name == "Rogue"){
                                <option value="@dojo.DojoId" selected>@dojo.Name</option>
                            }else{
                                <option value="@dojo.DojoId">@dojo.Name</option>
                            }
                        }
                    }
                </select>
                <span asp-validation-for="@Model.Ninja.DojoId" class="d-block pl-3 offset-3 text-danger"></span>
            </div>
            <div class="col-12 d-inline-block my-2">
                <label asp-for="@Model.Ninja.Description" class="d-inline-block col-3 p-0 align-top"></label>
                <textarea asp-for="@Model.Ninja.Description" class="form-control d-inline-block col-8 m-auto" placeholder="Enter Description" aria-label="Enter Description"></textarea>
                <span asp-validation-for="@Model.Ninja.Description" class="d-block pl-3 offset-3 text-danger"></span>
            </div>
            <div class="row my-2 pr-5 justify-content-end">
                <button class="btn btn-dark" type="submit">Add Ninja</button>
            </div>
        </form>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dojo_League</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/css/bootstrap.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
            <a class="navbar-brand" href="/Dashboard">Dojo League</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    @{ 
                        if(@ViewData["Title"]=="Ninjas"){
                            <li class="nav-item active">
                                <a class="nav-link" href="/">Ninjas <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Dojos">Dojos</a>
                            </li>
                        }else if(@ViewData["Title"]=="Dojos"){
                            <li class="nav-item">
                                <a class="nav-link" href="/">Ninjas</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="/Dojos">Dojos <span class="sr-only">(current)</span></a>
                            </li>
                        }else{
                            <li class="nav-item">
                                <a class="nav-link" href="/">Ninjas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Dojos">Dojos</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </nav>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery/dist/jquery-ui.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/jquery-ui.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery-ui.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>